# Generated by Django 4.1 on 2022-09-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_author_blog_date_blog_photo_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
    ]
