# Generated by Django 4.1 on 2022-09-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
        migrations.AddField(
            model_name='blog',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
